[workspace]
members = [
    "gguf",
    "tensor",
    "causal-lm",
    "models/llama/common",
    "models/llama/common-cpu",
    "test-utils",
]
resolver = "2"

[workspace.dependencies]
gguf.path = "gguf"
tensor.path = "tensor"
causal-lm.path = "causal-lm"
test-utils.path = "test-utils"

ggus = { git = "https://github.com/YdrMaster/gguf", rev = "e64d758" }
ggml-quants = { git = "https://github.com/YdrMaster/gguf", rev = "e64d758" }
ndarray-layout = { git = "https://github.com/YdrMaster/ndarray-layout", rev = "5c6b969" }
operators = { git = "https://github.com/YdrMaster/operators-rs", rev = "9b5c6b9", default-features = false }

memmap2 = "0.9"
