[workspace]
members = [
    "common",
    "tensor",
    "tokenizer",
    "transformer",
    "transformer-cpu",
    "nvidia/common",
    "nvidia/transformer",
    "nvidia/distributed",
    "service",
    "xtask",
]
resolver = "2"

[workspace.dependencies]
half = "2.4"
rayon = "1.9"
serde_json = "1.0"
serde = "1.0"
log = "0.4"
tokio = { version = "1.37", features = ["rt-multi-thread", "sync"] }

cuda = { path = "../cuda-driver/cuda" }
cublas = { path = "../cuda-driver/cublas" }
nccl = { path = "../cuda-driver/nccl" }
search-cuda-tools = { path = "../cuda-driver/search-cuda-tools" }
