[workspace]
members = [
    "common",
    "gguf",
    "tensor",
    "models/llama/common",
    "models/llama/common-cpu",
    "models/llama/nvidia-gpu",
    "models/llama/opencl",
    "test-utils",
]
resolver = "2"

[workspace.dependencies]
common.path = "common"
gguf.path = "gguf"
tensor.path = "tensor"
causal-lm.path = "causal-lm"
test-utils.path = "test-utils"

ggus = { git = "https://github.com/YdrMaster/gguf", rev = "0fe682f" }
ndarray-layout = { git = "https://github.com/YdrMaster/ndarray-layout", rev = "48d36c5" }
operators = { git = "https://github.com/YdrMaster/operators-rs", rev = "3f3075c", default-features = false }

build-script-cfg = "0.0"
search-cuda-tools = { git = "https://github.com/YdrMaster/cuda-driver", rev = "5a8d0c8" }
search-cl-tools = { git = "https://github.com/InfiniTensor/clrt", rev = "166aba1" }
