[package]
name = "test-utils"
version = "0.0.0"
edition.workspace = true
authors = ["YdrMaster <ydrml@hotmail.com>"]

[dependencies]
common.workspace = true
gguf.workspace = true
env_logger.workspace = true
cli-table = "0.4.9"
