[package]
name = "tensor"
version = "0.0.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]

[dependencies]
ggml-quants.workspace = true
ndarray-layout.workspace = true
operators.workspace = true
half = "2.4"
