[package]
name = "tokenizer"
version = "0.0.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap2.workspace = true
patricia_tree = "0.8"
tokeneer = { git = "https://github.com/YdrMaster/tokeneer", rev = "8a9c60d" }
